### PR TITLE
free from depending on underscore mixin _.isInt

### PR DESCRIPTION
**Pull request by patte**
My app crashed with the following error:

```
Uncaught Error: TypeError: undefined is not a function (evaluating '_.isInt(timeout)')
```

I tried to mixin isInt into underscore, but that didn't work either (same error).
lib/underscore_mixins.coffee

```
_.mixin isInteger: (s) ->
  parseInt(s, 10) == s
```

### CODE REVIEW

**Comment by zeroasterisk** [comment]
sure thing, simple enough conversion - thanks for the PR!

NOTE - that I'm not really using this plugin - it was an idea/experiment, meant to be a companion to the background geolocation plugin... but in practice I'm not really using it.

**Comment by patte** [comment]
thanks for merging! Can you please bump the version number of the package, so that I can switch back to this one and remove my fork from my app?
I tried mdg:geolocation but I'm really missing the feature to unwatch location updates, like others (https://github.com/cscott/mobile-packages/commit/2ca44285fa4431f87943378ad77d9245cb0ff0b3#commitcomment-9760235). How do you handle this?

**Comment by zeroasterisk** [comment]
version updated to 0.0.3

I think that, and 1-time checking were why I was thinking I'd use my own package.... but I think I've ignored it until now.

**Comment by patte** [comment]
thanks for the version bump. Sadly I can't find the version via meteor yet:

```
patte@pattesMBPR app ∴ meteor add zeroasterisk:cordova-geolocation-foreground@0.0.3
 => Errors while parsing arguments:

While adding package zeroasterisk:cordova-geolocation-foreground@0.0.3:
error: no such version zeroasterisk:cordova-geolocation-foreground@0.0.3
```

May you need to push it to meteor as well? I didn't release a package myself yet.

Ok. I think it's really strange that mdg:geolocation doesn't bring the functionality to unwatch. I would hate an app that drains my battery down even when it doesn't need location updates anymore... but yeah, thanks for your package!

**Comment by zeroasterisk** [comment]
versions bumped and should be ready (sorry for back-and-forth).

Published zeroasterisk:cordova-geolocation-foreground@0.0.3.
Published zeroasterisk:cordova-geolocation-background@0.0.6.

**Pull request merged**
